### ISSUE TITLE
Move to /multiformats org

### ISSUE THREAD

**Issue by lidel** [multiformats/js-uri-to-multiaddr#7]
This library is used by js-ipfs, and used by over 100 projects

 

TODO:

- [x] move to <del>ipfs-shipyard</del> multiformats org
- [x] add @alanshaw as co-owner on NPM    :running_man:  :dash: :bus:
- [x] https://github.com/tableflip/multiaddr-to-uri/issues/6

:ok_hand:

**Comment by alanshaw** [comment]
Should we move to `multiformats` instead? Also, prefix "js-" on repo name.

**Comment by lidel** [comment]
I'd say yes to both :+1:

**Comment by lidel** [comment]
@olizilla would it be ok to add @alanshaw and @lidel as contributors  at NPM?
https://www.npmjs.com/package/multiaddr-to-uri?

**Comment by alanshaw** [comment]
ping, lets finish this!

**Comment by lidel** [comment]
@olizilla?

**Comment by olizilla** [comment]
permissions granted
<img width="404" alt="Screenshot 2020-01-07 at 15 48 51" src="https://user-images.githubusercontent.com/58871/71908055-380c2780-3165-11ea-882a-b9dcc501f456.png">
